// <auto-generated />
using System;
using MainService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainService.Migrations
{
    [DbContext(typeof(MainServiceContext))]
    [Migration("20260515111733_AddLessonTypes")]
    partial class AddLessonTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrigadesDisciplines", b =>
                {
                    b.Property<int>("BrigadesBrigadeId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplinesDisciplineId")
                        .HasColumnType("integer");

                    b.HasKey("BrigadesBrigadeId", "DisciplinesDisciplineId");

                    b.HasIndex("DisciplinesDisciplineId");

                    b.ToTable("BrigadesDisciplines");
                });

            modelBuilder.Entity("BrigadesStudents", b =>
                {
                    b.Property<int>("BrigadesBrigadeId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("integer");

                    b.HasKey("BrigadesBrigadeId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("BrigadesStudents");
                });

            modelBuilder.Entity("DisciplinesGroups", b =>
                {
                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("DisciplineId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("DisciplinesGroups", (string)null);
                });

            modelBuilder.Entity("DisciplinesProfessors", b =>
                {
                    b.Property<int>("DisciplinesDisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorsProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("DisciplinesDisciplineId", "ProfessorsProfessorId");

                    b.HasIndex("ProfessorsProfessorId");

                    b.ToTable("DisciplinesProfessors");
                });

            modelBuilder.Entity("MainService.AcademicYears", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcademicYearId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AcademicYearId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("MainService.AttestationMarks", b =>
                {
                    b.Property<int>("AttestationMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationMarkId"));

                    b.Property<int>("AttestationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AttestationMarkId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("AttestationTypeId");

                    b.ToTable("AttestationMarks");
                });

            modelBuilder.Entity("MainService.AttestationTypes", b =>
                {
                    b.Property<int>("AttestationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AttestationTypeId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("AttestationTypes");
                });

            modelBuilder.Entity("MainService.Attestations", b =>
                {
                    b.Property<int>("AttestationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationId"));

                    b.Property<int?>("AttestationMarkId")
                        .HasColumnType("integer");

                    b.Property<int>("AttestationTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("AttestationId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("AttestationMarkId");

                    b.HasIndex("AttestationTypeId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attestations");
                });

            modelBuilder.Entity("MainService.Brigades", b =>
                {
                    b.Property<int>("BrigadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrigadeId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTemplateForGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("BrigadeId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("GroupId");

                    b.ToTable("Brigades");
                });

            modelBuilder.Entity("MainService.Curators", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ProfessorId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Curators", (string)null);
                });

            modelBuilder.Entity("MainService.Departments", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MainService.Disciplines", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<int?>("DisciplineRegisterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("DisciplineId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("DisciplineRegisterId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("MainService.DisciplinesRegisters", b =>
                {
                    b.Property<int>("DisciplineRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineRegisterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("DisciplineRegisterId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("DisciplinesRegisters");
                });

            modelBuilder.Entity("MainService.EmployeePosts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("EmployeePosts");
                });

            modelBuilder.Entity("MainService.Faculties", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("FacultyId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingDirectionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("FacultyId");

                    b.HasIndex("TrainingDirectionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MainService.LessonMarks", b =>
                {
                    b.Property<int>("LessonMarkId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("LessonMarkId", "MarkId", "StudentId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MarkId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonMarks");
                });

            modelBuilder.Entity("MainService.LessonPresences", b =>
                {
                    b.Property<int>("LessonPresenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonPresenceId"));

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("PresenceStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("LessonPresenceId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("LessonId");

                    b.HasIndex("PresenceStatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonPresences");
                });

            modelBuilder.Entity("MainService.LessonTypes", b =>
                {
                    b.Property<int>("LessonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("LessonTypeId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("LessonTypes");
                });

            modelBuilder.Entity("MainService.Lessons", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("LessonId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("LessonTypeId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MainService.MarkTypes", b =>
                {
                    b.Property<int>("MarkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarkTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UniversityEmployerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("MarkTypeId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("UniversityEmployerId");

                    b.ToTable("MarkTypes");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.Property<int>("MarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarkId"));

                    b.Property<int>("MarkTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("MarkId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("MarkTypeId", "Value")
                        .IsUnique();

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("MainService.NotesAboutStudent", b =>
                {
                    b.Property<int>("NotesAboutStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotesAboutStudentId"));

                    b.Property<int?>("DisciplinesDisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("NotesAboutStudentId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("DisciplinesDisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNotes");
                });

            modelBuilder.Entity("MainService.PresenceStatuses", b =>
                {
                    b.Property<int>("PresenceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PresenceStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("PresenceStatusId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("PresenceStatuses");
                });

            modelBuilder.Entity("MainService.Professors", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfessorId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityEmployerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ProfessorId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UniversityEmployerId");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("MainService.SelectedMarkTypes", b =>
                {
                    b.Property<int>("LessonTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("LessonTypeId", "MarkTypeId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("MarkTypeId");

                    b.ToTable("SelectedMarkTypes");
                });

            modelBuilder.Entity("MainService.Semesters", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("SemesterCode")
                        .HasColumnType("integer");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("SemesterId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("MainService.StudentPersons", b =>
                {
                    b.Property<int>("StudentPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentPersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("StudentPersonId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentPersons");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentCode")
                        .HasColumnType("integer");

                    b.Property<int>("StudentPersonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("StudentPersonId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MainService.TrainingDirections", b =>
                {
                    b.Property<int>("TrainingDirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingDirectionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("TrainingDirectionId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("TrainingDirections");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.Property<int>("UniversityEmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityEmployerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UniversityEmployerId");

                    b.HasAlternateKey("Uuid");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UniversityEmployers");
                });

            modelBuilder.Entity("MainService.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Uuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrigadesDisciplines", b =>
                {
                    b.HasOne("MainService.Brigades", null)
                        .WithMany()
                        .HasForeignKey("BrigadesBrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Disciplines", null)
                        .WithMany()
                        .HasForeignKey("DisciplinesDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrigadesStudents", b =>
                {
                    b.HasOne("MainService.Brigades", null)
                        .WithMany()
                        .HasForeignKey("BrigadesBrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplinesGroups", b =>
                {
                    b.HasOne("MainService.Disciplines", null)
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Groups", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplinesProfessors", b =>
                {
                    b.HasOne("MainService.Disciplines", null)
                        .WithMany()
                        .HasForeignKey("DisciplinesDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Professors", null)
                        .WithMany()
                        .HasForeignKey("ProfessorsProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainService.AttestationMarks", b =>
                {
                    b.HasOne("MainService.AttestationTypes", "AttestationType")
                        .WithMany("AttestationMarks")
                        .HasForeignKey("AttestationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttestationType");
                });

            modelBuilder.Entity("MainService.Attestations", b =>
                {
                    b.HasOne("MainService.AttestationMarks", "AttestationMark")
                        .WithMany("Attestation")
                        .HasForeignKey("AttestationMarkId");

                    b.HasOne("MainService.AttestationTypes", "AttestationType")
                        .WithMany("Attestations")
                        .HasForeignKey("AttestationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Disciplines", "Discipline")
                        .WithMany("Attestations")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("Attestations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttestationMark");

                    b.Navigation("AttestationType");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.Brigades", b =>
                {
                    b.HasOne("MainService.Groups", "Group")
                        .WithMany("Brigades")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MainService.Curators", b =>
                {
                    b.HasOne("MainService.Groups", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Professors", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MainService.Departments", b =>
                {
                    b.HasOne("MainService.Faculties", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("MainService.Disciplines", b =>
                {
                    b.HasOne("MainService.AcademicYears", "AcademicYear")
                        .WithMany("Disciplines")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.DisciplinesRegisters", "DisciplineRegister")
                        .WithMany("Disciplines")
                        .HasForeignKey("DisciplineRegisterId");

                    b.HasOne("MainService.Semesters", "Semester")
                        .WithMany("Disciplines")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("DisciplineRegister");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.HasOne("MainService.Faculties", "Faculty")
                        .WithMany("Groups")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.TrainingDirections", "TrainingDirection")
                        .WithMany("Groups")
                        .HasForeignKey("TrainingDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("TrainingDirection");
                });

            modelBuilder.Entity("MainService.LessonMarks", b =>
                {
                    b.HasOne("MainService.Lessons", "Lesson")
                        .WithMany("LessonMarks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Marks", "Mark")
                        .WithMany("LessonMarks")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("LessonMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Mark");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.LessonPresences", b =>
                {
                    b.HasOne("MainService.Lessons", "Lesson")
                        .WithMany("LessonPresences")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.PresenceStatuses", "PresenceStatus")
                        .WithMany("LessonPresences")
                        .HasForeignKey("PresenceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("LessonPresences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("PresenceStatus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.Lessons", b =>
                {
                    b.HasOne("MainService.Disciplines", "Discipline")
                        .WithMany("Lessons")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.LessonTypes", "LessonType")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("LessonType");
                });

            modelBuilder.Entity("MainService.MarkTypes", b =>
                {
                    b.HasOne("MainService.UniversityEmployers", "UniversityEmployer")
                        .WithMany("MarkTypes")
                        .HasForeignKey("UniversityEmployerId");

                    b.Navigation("UniversityEmployer");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.HasOne("MainService.MarkTypes", "MarkType")
                        .WithMany("Marks")
                        .HasForeignKey("MarkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkType");
                });

            modelBuilder.Entity("MainService.NotesAboutStudent", b =>
                {
                    b.HasOne("MainService.Disciplines", null)
                        .WithMany("NotesAboutStudent")
                        .HasForeignKey("DisciplinesDisciplineId");

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("NotesAboutStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.Professors", b =>
                {
                    b.HasOne("MainService.AcademicYears", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Departments", "Department")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MainService.EmployeePosts", "Post")
                        .WithMany("Professors")
                        .HasForeignKey("PostId");

                    b.HasOne("MainService.UniversityEmployers", "UniversityEmployer")
                        .WithMany("Professors")
                        .HasForeignKey("UniversityEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Department");

                    b.Navigation("Post");

                    b.Navigation("UniversityEmployer");
                });

            modelBuilder.Entity("MainService.SelectedMarkTypes", b =>
                {
                    b.HasOne("MainService.Disciplines", "Discipline")
                        .WithMany("SelectedMarkTypes")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.LessonTypes", "LessonType")
                        .WithMany("SelectedMarkTypes")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.MarkTypes", "MarkType")
                        .WithMany()
                        .HasForeignKey("MarkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("LessonType");

                    b.Navigation("MarkType");
                });

            modelBuilder.Entity("MainService.StudentPersons", b =>
                {
                    b.HasOne("MainService.Users", "User")
                        .WithOne("StudentPerson")
                        .HasForeignKey("MainService.StudentPersons", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.HasOne("MainService.Groups", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.StudentPersons", "StudentPerson")
                        .WithMany("Students")
                        .HasForeignKey("StudentPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("StudentPerson");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.HasOne("MainService.Users", "User")
                        .WithOne("UniversityEmployer")
                        .HasForeignKey("MainService.UniversityEmployers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.AcademicYears", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("MainService.AttestationMarks", b =>
                {
                    b.Navigation("Attestation");
                });

            modelBuilder.Entity("MainService.AttestationTypes", b =>
                {
                    b.Navigation("AttestationMarks");

                    b.Navigation("Attestations");
                });

            modelBuilder.Entity("MainService.Departments", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("MainService.Disciplines", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("Lessons");

                    b.Navigation("NotesAboutStudent");

                    b.Navigation("SelectedMarkTypes");
                });

            modelBuilder.Entity("MainService.DisciplinesRegisters", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("MainService.EmployeePosts", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("MainService.Faculties", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.Navigation("Brigades");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MainService.LessonTypes", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("SelectedMarkTypes");
                });

            modelBuilder.Entity("MainService.Lessons", b =>
                {
                    b.Navigation("LessonMarks");

                    b.Navigation("LessonPresences");
                });

            modelBuilder.Entity("MainService.MarkTypes", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.Navigation("LessonMarks");
                });

            modelBuilder.Entity("MainService.PresenceStatuses", b =>
                {
                    b.Navigation("LessonPresences");
                });

            modelBuilder.Entity("MainService.Semesters", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("MainService.StudentPersons", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("LessonMarks");

                    b.Navigation("LessonPresences");

                    b.Navigation("NotesAboutStudent");
                });

            modelBuilder.Entity("MainService.TrainingDirections", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.Navigation("MarkTypes");

                    b.Navigation("Professors");
                });

            modelBuilder.Entity("MainService.Users", b =>
                {
                    b.Navigation("StudentPerson");

                    b.Navigation("UniversityEmployer");
                });
#pragma warning restore 612, 618
        }
    }
}
