// <auto-generated />
using System;

using MainService;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainService.Migrations
{
    [DbContext(typeof(MainServiceContext))]
    [Migration("20260508165906_AddEntitiesOfAttestation")]
    partial class AddEntitiesOfAttestation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrigadesStudents", b =>
                {
                    b.Property<int>("BrigadesBrigadeId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("integer");

                    b.HasKey("BrigadesBrigadeId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("BrigadesStudents");
                });

            modelBuilder.Entity("MainService.AcademicYears", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcademicYearId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("AcademicYearId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("MainService.AttestationMarks", b =>
                {
                    b.Property<int>("AttestationMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationMarkId"));

                    b.Property<int>("AttestationId")
                        .HasColumnType("integer");

                    b.Property<int>("AttestationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttestationMarkId");

                    b.HasIndex("AttestationId");

                    b.HasIndex("AttestationTypeId");

                    b.ToTable("AttestationMarks");
                });

            modelBuilder.Entity("MainService.AttestationTypes", b =>
                {
                    b.Property<int>("AttestationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttestationTypeId");

                    b.ToTable("AttestationTypes");
                });

            modelBuilder.Entity("MainService.Attestations", b =>
                {
                    b.Property<int>("AttestationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttestationId"));

                    b.Property<int>("AttestationTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("AttestationId");

                    b.HasIndex("AttestationTypeId");

                    b.ToTable("Attestations");
                });

            modelBuilder.Entity("MainService.Brigades", b =>
                {
                    b.Property<int>("BrigadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrigadeId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupsGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BrigadeId");

                    b.HasIndex("GroupsGroupId");

                    b.ToTable("Brigades");
                });

            modelBuilder.Entity("MainService.Departments", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FacultiesFacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.HasIndex("FacultiesFacultyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MainService.Disciplines", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<int?>("BrigadesBrigadeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DisciplineId");

                    b.HasIndex("BrigadesBrigadeId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("MainService.DisciplinesRegisters", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DisciplineId");

                    b.ToTable("DisciplinesRegisters");
                });

            modelBuilder.Entity("MainService.EmployeePosts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostId");

                    b.ToTable("EmployeePosts");
                });

            modelBuilder.Entity("MainService.Faculties", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrainingDirectionId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.HasIndex("TrainingDirectionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MainService.LessonMarks", b =>
                {
                    b.Property<int>("LessonMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonMarkId"));

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("LessonMarkId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MarkId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonMarks");
                });

            modelBuilder.Entity("MainService.LessonPresences", b =>
                {
                    b.Property<int>("LessonPresenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonPresenceId"));

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int?>("PresenceStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("LessonPresenceId");

                    b.HasIndex("LessonId");

                    b.HasIndex("PresenceStatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonPresences");
                });

            modelBuilder.Entity("MainService.Lessons", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LessonId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.Property<int>("MarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarkId"));

                    b.Property<int?>("MarkTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MarkId");

                    b.HasIndex("MarkTypeId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("MainService.PresenceStatuses", b =>
                {
                    b.Property<int>("PresenceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PresenceStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PresenceStatusId");

                    b.ToTable("PresenceStatuses");
                });

            modelBuilder.Entity("MainService.Professors", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfessorId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityEmployerId")
                        .HasColumnType("integer");

                    b.HasKey("ProfessorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UniversityEmployerId")
                        .IsUnique();

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("MainService.Semesters", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("SemesterCode")
                        .HasColumnType("integer");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("MainService.StudentNotes", b =>
                {
                    b.Property<int>("StudentNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentNoteId"));

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("StudentNoteId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNotes");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrainingDirectionsTrainingDirectionId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TrainingDirectionsTrainingDirectionId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MainService.TrainingDirections", b =>
                {
                    b.Property<int>("TrainingDirectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingDirectionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrainingDirectionId");

                    b.ToTable("TrainingDirections");
                });

            modelBuilder.Entity("MainService.MarkTypes", b =>
                {
                    b.Property<int>("MarkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarkTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MarkTypeId");

                    b.ToTable("MarkTypes");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.Property<int>("UniversityEmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityEmployerId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UniversityEmployerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UniversityEmployers");
                });

            modelBuilder.Entity("MainService.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("UserUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("StudentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrigadesStudents", b =>
                {
                    b.HasOne("MainService.Brigades", null)
                        .WithMany()
                        .HasForeignKey("BrigadesBrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainService.AttestationMarks", b =>
                {
                    b.HasOne("MainService.Attestations", "Attestation")
                        .WithMany("AttestationMarks")
                        .HasForeignKey("AttestationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.AttestationTypes", "AttestationType")
                        .WithMany("AttestationMarks")
                        .HasForeignKey("AttestationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attestation");

                    b.Navigation("AttestationType");
                });

            modelBuilder.Entity("MainService.Attestations", b =>
                {
                    b.HasOne("MainService.AttestationTypes", "AttestationType")
                        .WithMany("Attestations")
                        .HasForeignKey("AttestationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttestationType");
                });

            modelBuilder.Entity("MainService.Brigades", b =>
                {
                    b.HasOne("MainService.Groups", "Groups")
                        .WithMany("Brigades")
                        .HasForeignKey("GroupsGroupId");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MainService.Departments", b =>
                {
                    b.HasOne("MainService.Faculties", null)
                        .WithMany("Departments")
                        .HasForeignKey("FacultiesFacultyId");
                });

            modelBuilder.Entity("MainService.Disciplines", b =>
                {
                    b.HasOne("MainService.Brigades", null)
                        .WithMany("Notes")
                        .HasForeignKey("BrigadesBrigadeId");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.HasOne("MainService.TrainingDirections", "TrainingDirection")
                        .WithMany("Groups")
                        .HasForeignKey("TrainingDirectionId");

                    b.Navigation("TrainingDirection");
                });

            modelBuilder.Entity("MainService.LessonMarks", b =>
                {
                    b.HasOne("MainService.Lessons", "Lesson")
                        .WithMany("LessonMarks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Marks", "Mark")
                        .WithMany("LessonMarks")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("LessonMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Mark");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.LessonPresences", b =>
                {
                    b.HasOne("MainService.Lessons", "Lesson")
                        .WithMany("LessonPresences")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.PresenceStatuses", "PresenceStatus")
                        .WithMany("LessonPresences")
                        .HasForeignKey("PresenceStatusId");

                    b.HasOne("MainService.Students", "Student")
                        .WithMany("LessonPresences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("PresenceStatus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.HasOne("MainService.MarkTypes", "MarkType")
                        .WithMany("Marks")
                        .HasForeignKey("MarkTypeId");

                    b.Navigation("MarkType");
                });

            modelBuilder.Entity("MainService.Professors", b =>
                {
                    b.HasOne("MainService.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MainService.EmployeePosts", "Post")
                        .WithMany("Professors")
                        .HasForeignKey("PostId");

                    b.HasOne("MainService.UniversityEmployers", "UniversityEmployer")
                        .WithOne("Professor")
                        .HasForeignKey("MainService.Professors", "UniversityEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Post");

                    b.Navigation("UniversityEmployer");
                });

            modelBuilder.Entity("MainService.StudentNotes", b =>
                {
                    b.HasOne("MainService.Students", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.HasOne("MainService.Groups", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.HasOne("MainService.TrainingDirections", null)
                        .WithMany("Students")
                        .HasForeignKey("TrainingDirectionsTrainingDirectionId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.HasOne("MainService.Users", "User")
                        .WithOne("UniversityEmployer")
                        .HasForeignKey("MainService.UniversityEmployers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.Users", b =>
                {
                    b.HasOne("MainService.Students", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MainService.AttestationTypes", b =>
                {
                    b.Navigation("AttestationMarks");

                    b.Navigation("Attestations");
                });

            modelBuilder.Entity("MainService.Attestations", b =>
                {
                    b.Navigation("AttestationMarks");
                });

            modelBuilder.Entity("MainService.Brigades", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MainService.EmployeePosts", b =>
                {
                    b.Navigation("Professors");
                });

            modelBuilder.Entity("MainService.Faculties", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MainService.Groups", b =>
                {
                    b.Navigation("Brigades");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MainService.Lessons", b =>
                {
                    b.Navigation("LessonMarks");

                    b.Navigation("LessonPresences");
                });

            modelBuilder.Entity("MainService.Marks", b =>
                {
                    b.Navigation("LessonMarks");
                });

            modelBuilder.Entity("MainService.PresenceStatuses", b =>
                {
                    b.Navigation("LessonPresences");
                });

            modelBuilder.Entity("MainService.Students", b =>
                {
                    b.Navigation("LessonMarks");

                    b.Navigation("LessonPresences");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MainService.TrainingDirections", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MainService.MarkTypes", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("MainService.UniversityEmployers", b =>
                {
                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MainService.Users", b =>
                {
                    b.Navigation("UniversityEmployer");
                });
#pragma warning restore 612, 618
        }
    }
}
