
http {
    
    upstream auth_services { 
        server auth-service:9091;
        keepalive 32;
    };

    upstream main_services {
        server main-service:9091;
        keepalive 32;
    };

    server {
        listen 9090;
        server_name api.journal.gateway;

        # subrequest для auth_request (не пересекается с публичным /auth/*)
        location = /_verify {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Authorization $http_authorization;
            proxy_method POST;
            proxy_pass http://auth_services/auth;
        }

        # все /auth/* в auth_service без префикса /auth
        location ^~ /auth {
            auth_request /_verify;
            auth_request_set $auth_json $upstream_http_x_error_json;
            auth_request_set $trace_id $upstream_http_x_trace_id;
            auth_request_set $user_id $upstream_http_x_user_id;

            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-Trace-Id $trace_id;

            proxy_pass http://auth_services/;

            error_page 401 = @err401;
        }

        # все /main/* в main_service без префикса /main
        location ^~ /main {
            auth_request /_verify;
            auth_request_set $auth_json $upstream_http_x_error_json;
            auth_request_set $trace_id $upstream_http_x_trace_id;
            auth_request_set $user_id $upstream_http_x_user_id;

            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-Trace-Id $trace_id;

            proxy_pass http://main_services/;

            error_page 401 = @err401;
        }

        location @err401 {
            internal;
            default_type application/json;
            add_header X-Trace-Id $trace_id;
            return 401 $auth_json;
        }
    }
}