
http {
    
    upstream auth_services { 
        server auth-service:9091;
        keepalive 32;

    };
    
    upstream gateway_service {
        server api.gateway:9091;
        keepalive 32;
    };

    server {
        listen 9090;
        server_name api.journal.check-auth;

        location /auth {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Authorization $http_authorization;
            proxy_method POST;
            proxy_pass http://auth_services/auth;
        }

        location / {
            auth_request /auth;
            # из ответа в пременные
            auth_request_set $auth_json $upstream_http_x_error_json;
            auth_request_set $trace_id $upstream_http_x_trace_id;
            auth_request_set $user_id $upstream_http_x_user_id;
            
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            # Понадобиться позже
            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-Trace-Id $trace_id;
            
            proxy_pass http://gateway_service;

            error_page 401 = @err401;
        }

        location @err401 {
            internal;
            default_type application/json;
            add_header X-Trace-Id $trace_id;
            return 401 $auth_json;
        }
    }
}

