import type { Metadata } from "next"
import "./main.css"
import { ClientThemeProvider } from "@/shared/model/client-theme-provider"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter"
export const metadata: Metadata = {
	title: "Авторизация",
	description: "Generated by create next app",
}

export default function RootLayout(props: { children: React.ReactNode }) {
	const { children } = props
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider options={{ enableCssLayer: true }}>
					<ClientThemeProvider>{children}</ClientThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
