import type { Metadata } from "next";
import "./main.css";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html suppressHydrationWarning>
      <body className="m-auto content-center">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
