import type { Metadata } from "next"
import "./main.css"
import { ClientThemeProvider } from "@/shared/lib/client-theme-provider"
export const metadata: Metadata = {
	title: "Авторизация",
	description: "Generated by create next app",
}

export default function RootLayout(props: { children: React.ReactNode }) {
	const { children } = props
	return (
		<html suppressHydrationWarning>
			<body>
				<ClientThemeProvider>{children}</ClientThemeProvider>
			</body>
		</html>
	)
}
