
http { 
    
    upstream main_services {
        server main-service:9091;
        keepalive 32;
    }

    upstream auth_service {
        server auth-service:9091;
        keepalive 32;
    }

    server {
        listen 9090;
        server_name api.journal.gateway;

        # все /auth/* → auth_service без префикса /auth
        location ^~ /auth {
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            # Понадобиться позже
            proxy_set_header X-User-Id $http_x_user_id;
            proxy_set_header X-Trace-Id $http_x_trace_id;
            
            proxy_pass http://auth_service/;
        }

        # все /main/* → main_service без префикса /main
        location ^~ /main {
             proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            # Понадобиться позже
            proxy_set_header X-User-Id $http_x_user_id;
            proxy_set_header X-Trace-Id $http_x_trace_id;
            
            proxy_pass http://main_services/;
        }
    }
}